spring:
  datasource:
    url: jdbc:mysql://8.130.142.163:3306/mybatis?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: mybatis
    password: 2LjJrpkGmKATCstb
  devtools:
    restart:
      enabled: false

knife4j:
  enable: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: WARN
    org.example.helloworld: INFO
    org.springframework.web: WARN

