spring:
  application:
    name: helloworld
  profiles:
    active: test
  devtools:
    restart:
      additional-paths: src/main/java
  web:
    resources:
      static-locations: /upload/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: MySecretKeyForJWT2024SpringBootMyBatisPlusTemplate
  expiration: 86400000

knife4j:
  setting:
    language: zh-cn

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-flat-param-object: true

aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:oss-cn-hangzhou.aliyuncs.com}
    accessKeyId: ${ALIYUN_OSS_ACCESS_KEY_ID:}
    accessKeySecret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:}
    bucketName: ${ALIYUN_OSS_BUCKET_NAME:hellojavajava}
    urlPrefix: ${ALIYUN_OSS_URL_PREFIX:}
